//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensajes", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Mensajes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        private int PrioridadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodigoPais {
            get {
                return this.CodigoPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPaisField, value) != true)) {
                    this.CodigoPaisField = value;
                    this.RaisePropertyChanged("CodigoPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Prioridad {
            get {
                return this.PrioridadField;
            }
            set {
                if ((this.PrioridadField.Equals(value) != true)) {
                    this.PrioridadField = value;
                    this.RaisePropertyChanged("Prioridad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.WS_MensajesSoap")]
    public interface WS_MensajesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pMensaje del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Enviar", ReplyAction="*")]
        SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarResponse Enviar(SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Enviar", ReplyAction="*")]
        System.Threading.Tasks.Task<SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarResponse> EnviarAsync(SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enviar", Namespace="http://tempuri.org/", Order=0)]
        public SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequestBody Body;
        
        public EnviarRequest() {
        }
        
        public EnviarRequest(SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.Mensajes pMensaje;
        
        public EnviarRequestBody() {
        }
        
        public EnviarRequestBody(SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.Mensajes pMensaje) {
            this.pMensaje = pMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarResponse", Namespace="http://tempuri.org/", Order=0)]
        public SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarResponseBody Body;
        
        public EnviarResponse() {
        }
        
        public EnviarResponse(SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.ArrayOfString EnviarResult;
        
        public EnviarResponseBody() {
        }
        
        public EnviarResponseBody(SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.ArrayOfString EnviarResult) {
            this.EnviarResult = EnviarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_MensajesSoapChannel : SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.WS_MensajesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_MensajesSoapClient : System.ServiceModel.ClientBase<SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.WS_MensajesSoap>, SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.WS_MensajesSoap {
        
        public WS_MensajesSoapClient() {
        }
        
        public WS_MensajesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_MensajesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_MensajesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_MensajesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarResponse SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.WS_MensajesSoap.Enviar(SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequest request) {
            return base.Channel.Enviar(request);
        }
        
        public SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.ArrayOfString Enviar(SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.Mensajes pMensaje) {
            SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequest inValue = new SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequest();
            inValue.Body = new SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequestBody();
            inValue.Body.pMensaje = pMensaje;
            SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarResponse retVal = ((SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.WS_MensajesSoap)(this)).Enviar(inValue);
            return retVal.Body.EnviarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarResponse> SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.WS_MensajesSoap.EnviarAsync(SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequest request) {
            return base.Channel.EnviarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarResponse> EnviarAsync(SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.Mensajes pMensaje) {
            SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequest inValue = new SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequest();
            inValue.Body = new SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.EnviarRequestBody();
            inValue.Body.pMensaje = pMensaje;
            return ((SchoolManager.WhatsApp.ServiciosWeb.WS_Mensajes.WS_MensajesSoap)(this)).EnviarAsync(inValue);
        }
    }
}
